server:
  port: 7003
eureka:
  instance:
    #eureka的服务端实例的名称
    hostname: localhost
  client:
    #false表示不向实例注册中心注册自己
    register-with-eureka: false
    #false表示当前自己就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/